### ISSUE TITLE
Template 9 and 3

### ISSUE THREAD

**Issue by saist1993** [SmartDataAnalytics/QueryDataSet#1]
Fix template 9 from 
```{ <%(e_in_in)s> <%(e_in_in_to_e_in)s> ?x . ?x <%(e_in_to_e)s> ?uri } ```
to 
```{ <%(e_in_in)s> <%(e_in_in_to_e_in)s> ?x . ?x <%(e_in_in_to_e_in)s> ?uri } ```

Also interchange 3 and 303

**Comment by geraltofrivia** [comment]
All templates are updated and fixed. 
The issue mentioned above is not incorrect btw.
