### ISSUE TITLE
Minor template issues

### ISSUE THREAD

**Issue by akaha** [SmartDataAnalytics/QueryDataSet#2]
The bracket of the where-clause ends too early in templates: 302, 306, 315, 316, 402, 405, 407 and 408.
The templates 303, 307 and 403 don't fit with the corresponding questions. They need one more triple:
303: `?x rdf:type class`
307: `?uri rdf:type class`
403: `?x rdf:type class`
In the dataset templates are referenced that don't exist: 11, 601, 605, 906.

**Comment by geraltofrivia** [comment]
All templates are fixed in recent changes. 
Thanks for the heads up, @akaha
