### ISSUE TITLE
only 1369 (not 5042) in entities.txt

### ISSUE THREAD

**Issue by knightmarehs** [SmartDataAnalytics/QueryDataSet#4]
**Describe the bug**
http://lc-quad.sda.tech/ says 5042 entities covered while only 1369 in entities.txt

**Comment by geraltofrivia** [comment]
Hi. 
So, 5042 is the total number of entities in all of the SPARQL.
1369 is the number of entities intended as the answer, while creating the SPARQL.

So, say `dbr:Germany` is one of the entities in entities.txt, then we'd generate the subgraph around it, and juxtapose that on SPRAQL templates. Let's say one of the SPARQL is:
```
SELECT ?uri WHERE { ?uri dbo:language dbr:German_language . }
```

Here, the entity `dbr:German_language` might not be mentioned in entities.txt, but it still comes up in the SPARQL, and thus would count towards that 5042 number.

Apologies for any confusion, as well as delayed response.

**Comment by knightmarehs** [comment]
Thanks for your reply, I get it.
